# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c6ad6a9a3c7b84562dc9cc959df259600fbb2ef814851ef99e5195c2e908cf9da535e2706cb3a9dcdc8e2115dfa19a8a33e3b0daa75ec39f6110c195e569933

test:
  secret_key_base: 3405903066dc6968cd4b95110254604443a187dd2523d912be58491ec2af2e20e11e201d276b575206219b581a1ddc39d473ef14c843c8f97ac4397b514f5f12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
